### ISSUE TITLE
数据库表列表页不支持分页

### ISSUE THREAD

**Issue by ethantang1024** [huzhicheng/kite-mybatis-builder#3]
,我的表太多了,列表页只显示了一部分,有些表看不到,无法选择.
![image](https://user-images.githubusercontent.com/23518028/39162134-9a17f7e2-47a6-11e8-82f4-c61ddf71252f.png)
我有50张表,但列表页没有50项之多,也没有翻页按钮

**Comment by huzhicheng** [comment]
@yangzhaoyunfei  是没有加分页，但是可以下拉浏览器滚动条。
